# Generated by Django 3.1.4 on 2021-09-25 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('common_name', models.CharField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('names', models.JSONField()),
                ('topLevelDomain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
                ('alpha2Code', models.CharField(max_length=2)),
                ('numericCode', models.IntegerField()),
                ('alpha3Code', models.CharField(max_length=3)),
                ('cioc', models.CharField(max_length=3)),
                ('independent', models.BooleanField()),
                ('status', models.CharField(max_length=50)),
                ('unMember', models.BooleanField()),
                ('currencies', models.JSONField()),
                ('callingCodes', models.JSONField()),
                ('capital', models.CharField(max_length=20)),
                ('altSpellings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('languages', models.JSONField()),
                ('translations', models.JSONField()),
                ('latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('landlocked', models.BooleanField()),
                ('borders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('area', models.FloatField()),
                ('demonym', models.JSONField()),
            ],
        ),
    ]
