# Generated by Django 3.1.4 on 2021-09-19 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('topLevelDomain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
                ('alpha2Code', models.CharField(max_length=2)),
                ('alpha3Code', models.CharField(max_length=3)),
                ('callingCodes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('capital', models.CharField(max_length=20)),
                ('altSpellings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('demonym', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('gini', models.FloatField()),
                ('timezones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('borders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('nativeName', models.CharField(max_length=100)),
                ('numericCode', models.IntegerField()),
                ('currencies', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('translations', models.JSONField()),
                ('regionalBlocs', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('cioc', models.CharField(max_length=3)),
            ],
        ),
    ]
