# Generated by Django 3.1.4 on 2021-09-25 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
        ),
    ]
