# Generated by Django 3.1.4 on 2021-09-25 06:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography_api', '0002_auto_20210925_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), null=True, size=None),
        ),
    ]
