# Generated by Django 3.1.4 on 2021-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography_api', '0003_auto_20210925_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cioc',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
