# Generated by Django 3.1.4 on 2021-09-25 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography_api', '0005_auto_20210925_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3Code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='altSpellings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='callingCodes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencies',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='demonym',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='independent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='landlocked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='latlng',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='numericCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='topLevelDomain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='translations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='unMember',
            field=models.BooleanField(null=True),
        ),
    ]
