# Generated by Django 3.1.4 on 2021-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography_api', '0006_auto_20210925_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
