version: "3.9"
services:
  web-api:
    build: .
    depends_on:
      - psql_db
    container_name: velkozz_api
    networks:
      - velkozz-api-network      
    env_file: 
      - prod_db.env
    ports:
      - "80:80"
  
  psql_db:
    image: postgres
    container_name: velkoz_psql_backend
    restart: always
    networks:
      - velkozz-api-network
    env_file:
      - prod_db.env
    ports:
      - "5432:5432"
    volumes: 
       # Persist the data between container invocations
       - ~/velkozz_db/api_psql:/var/lib/postgresql/data
         
# Network configuration for API service: 
networks:
  velkozz-api-network: 
