version: "3.9"
services:
  web-api:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - psql_db
      - timescale_db
    container_name: velkozz_api
    networks:
      - velkozz-api-network      
    env_file: 
      - local_prod.env
      - prod_db.env
    ports:
      - "8000:8000"
  
  psql_db:
    image: postgres
    container_name: velkoz_psql_backend
    restart: always
    networks:
      - velkozz-api-network
    env_file:
      - prod_db.env
      - local_prod.env
    ports:
      - "5432:5432"
    volumes: 
       # Persist the data between container invocations
       - ~/velkozz_db/api_psql:/var/lib/postgresql/data
        
  timescale_db:
    image: timescale/timescaledb:latest-pg12
    container_name: velkozz_timescale_db
    restart: always
    networks:
      - velkozz-api-network
    env_file: 
      - timescale_db.env
    ports:      
      - "5431:5431"
    volumes: 
      # Persist the data between container invocations
      - ~/velkozz_db/timescale_db:/var/lib/postgresql/data
       
# Network configuration for API service: 
networks:
  velkozz-api-network: 
