version: "3.9"
services:
  
  web-api:
    build: .
    volumes: 
      - ~/staticroot:/staticroot
    depends_on:
      - psql_db
    container_name: velkozz_api
    networks:
      - velkozz-api-network      
    env_file: 
      - prod_db.env
  
  psql_db:
    image: postgres
    container_name: velkoz_psql_backend
    restart: always
    networks:
      - velkozz-api-network
    env_file:
      - prod_db.env
    volumes: 
       # Persist the data between container invocations
       - ~/velkozz_db/api_psql:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    volumes: 
      - ~/staticroot:/staticroot
    networks:
      - velkozz-api-network
    ports:
      - "80:80"
    depends_on:
      - web-api

# Network configuration for API service: 
networks:
  velkozz-api-network: 
