# Generated by Django 3.1.5 on 2021-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJIAIndexComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, unique=True)),
                ('exchange', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('industry', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField()),
                ('notes', models.CharField(max_length=200, null=True)),
                ('weighting', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'DJIA Market Index Composition',
            },
        ),
        migrations.CreateModel(
            name='FTSE100IndexComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('industry', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'FTSE 100 Market Index Composition',
            },
        ),
        migrations.CreateModel(
            name='SMIComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('company', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('canton', models.CharField(max_length=100)),
                ('weighting', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Swiss Market Index Composition',
            },
        ),
        migrations.CreateModel(
            name='SPIComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('smi_family', models.CharField(max_length=100, null=True)),
                ('date_added', models.CharField(max_length=10, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Swiss Performance Index Composition',
            },
        ),
        migrations.CreateModel(
            name='SPTSXIndexComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'S&P/TSX Market Index Composition',
            },
        ),
        migrations.CreateModel(
            name='SPYIndexComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('security_name', models.CharField(max_length=100, unique=True)),
                ('gics_sector', models.CharField(max_length=100, null=True)),
                ('gics_sub_industry', models.CharField(max_length=100, null=True)),
                ('headquarters_location', models.CharField(max_length=100, null=True)),
                ('date_added', models.CharField(max_length=25, null=True)),
                ('cik', models.IntegerField(unique=True)),
                ('founded', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SPY Market Index Composition',
            },
        ),
    ]
