# Generated by Django 3.1.3 on 2021-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0003_auto_20210216_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldNewsPosts',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(null=True)),
                ('upvote_ratio', models.FloatField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('num_comments', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
                ('stickied', models.BooleanField(null=True)),
                ('over_18', models.BooleanField(null=True)),
                ('spoiler', models.BooleanField(null=True)),
                ('author_is_gold', models.BooleanField(null=True)),
                ('author_mod', models.BooleanField(null=True)),
                ('author_has_verified_email', models.BooleanField(null=True)),
                ('permalink', models.CharField(max_length=300, null=True)),
                ('author', models.CharField(max_length=300)),
                ('author_created', models.DateTimeField()),
                ('comment_karma', models.IntegerField(null=True)),
                ('subreddit', models.CharField(default='world_news', editable=False, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'World News Subreddit Posts',
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
