# Generated by Django 3.1.3 on 2021-03-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0006_auto_20210329_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadaposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='canadaposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='canadaposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chinaposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chinaposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chinaposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='conflictnewsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='conflictnewsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conflictnewsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='conservativeposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='conservativeposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conservativeposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrencyposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrencyposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrencyposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='democratsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='democratsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='democratsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='economicsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='economicsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='economicsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='energyposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='energyposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='energyposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hongkongposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hongkongposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hongkongposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='indiaposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='indiaposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='indiaposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='israelposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='israelposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='israelposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='japanposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='japanposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='japanposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='koreaposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='koreaposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='koreaposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='liberalposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='liberalposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='liberalposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='libertarianposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='libertarianposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='libertarianposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='malaysiaposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='malaysiaposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='malaysiaposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='middleeastnewsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='middleeastnewsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='middleeastnewsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='neutralpoliticsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='neutralpoliticsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='neutralpoliticsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='northkoreanewsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='northkoreanewsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='northkoreanewsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='northkoreaposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='northkoreaposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='northkoreaposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pakistanposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pakistanposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pakistanposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='palestineposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='palestineposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='palestineposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='politicsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='politicsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='politicsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='progressiveposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='realtechposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='realtechposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='realtechposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scienceposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scienceposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scienceposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='singaporeposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='singaporeposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='singaporeposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='socialismposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='socialismposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='socialismposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spaceposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spaceposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='spaceposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='taiwanposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='taiwanposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taiwanposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='technologyposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='technologyposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='technologyposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='techposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='techposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thailandposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thailandposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='thailandposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ukpoliticsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ukpoliticsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ukpoliticsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wallstreetbetsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wallstreetbetsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallstreetbetsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='worldnewsposts',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='worldnewsposts',
            name='author_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worldnewsposts',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
