# Generated by Django 3.1.4 on 2021-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0008_indeedjobposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indeedjobposts',
            options={'verbose_name_plural': 'Indeed Job Posts'},
        ),
        migrations.AlterField(
            model_name='indeedjobposts',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
