# Generated by Django 3.1.4 on 2021-08-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0009_auto_20210510_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyYoutubeChannelStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=120)),
                ('channel_name', models.CharField(max_length=100)),
                ('total_views', models.IntegerField()),
                ('total_subscribers', models.IntegerField()),
                ('total_videos', models.IntegerField()),
                ('date_extracted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Youtube Channel Statistics',
                'ordering': ['date_extracted'],
            },
        ),
    ]
