# Generated by Django 3.1.4 on 2021-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0011_auto_20210812_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPosts',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, null=True)),
                ('subreddit', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('upvote_ratio', models.FloatField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('num_comments', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
                ('stickied', models.BooleanField(null=True)),
                ('over_18', models.BooleanField(null=True)),
                ('spoiler', models.BooleanField(null=True)),
                ('author_is_gold', models.BooleanField(null=True)),
                ('author_mod', models.BooleanField(null=True)),
                ('author_has_verified_email', models.BooleanField(null=True)),
                ('permalink', models.CharField(max_length=300, null=True)),
                ('author', models.CharField(max_length=300, null=True)),
                ('author_created', models.DateTimeField(null=True)),
                ('comment_karma', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Reddit Posts',
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CanadaPosts',
        ),
        migrations.DeleteModel(
            name='ChinaPosts',
        ),
        migrations.DeleteModel(
            name='ConflictNewsPosts',
        ),
        migrations.DeleteModel(
            name='ConservativePosts',
        ),
        migrations.DeleteModel(
            name='CryptoCurrencyPosts',
        ),
        migrations.DeleteModel(
            name='DemocratsPosts',
        ),
        migrations.DeleteModel(
            name='EconomicsPosts',
        ),
        migrations.DeleteModel(
            name='EnergyPosts',
        ),
        migrations.DeleteModel(
            name='HongKongPosts',
        ),
        migrations.DeleteModel(
            name='IndiaPosts',
        ),
        migrations.DeleteModel(
            name='IsraelPosts',
        ),
        migrations.DeleteModel(
            name='JapanPosts',
        ),
        migrations.DeleteModel(
            name='KoreaPosts',
        ),
        migrations.DeleteModel(
            name='LiberalPosts',
        ),
        migrations.DeleteModel(
            name='LibertarianPosts',
        ),
        migrations.DeleteModel(
            name='MalaysiaPosts',
        ),
        migrations.DeleteModel(
            name='MiddleEastNewsPosts',
        ),
        migrations.DeleteModel(
            name='NeutralPoliticsPosts',
        ),
        migrations.DeleteModel(
            name='NewsPosts',
        ),
        migrations.DeleteModel(
            name='NorthKoreaNewsPosts',
        ),
        migrations.DeleteModel(
            name='NorthKoreaPosts',
        ),
        migrations.DeleteModel(
            name='PakistanPosts',
        ),
        migrations.DeleteModel(
            name='PalestinePosts',
        ),
        migrations.DeleteModel(
            name='PoliticsPosts',
        ),
        migrations.DeleteModel(
            name='ProgressivePosts',
        ),
        migrations.DeleteModel(
            name='RealTechPosts',
        ),
        migrations.DeleteModel(
            name='SciencePosts',
        ),
        migrations.DeleteModel(
            name='SingaporePosts',
        ),
        migrations.DeleteModel(
            name='SocialismPosts',
        ),
        migrations.DeleteModel(
            name='SpacePosts',
        ),
        migrations.DeleteModel(
            name='TaiwanPosts',
        ),
        migrations.DeleteModel(
            name='TechnologyPosts',
        ),
        migrations.DeleteModel(
            name='TechPosts',
        ),
        migrations.DeleteModel(
            name='ThailandPosts',
        ),
        migrations.DeleteModel(
            name='UKPoliticsPosts',
        ),
        migrations.DeleteModel(
            name='WallStreetBetsPosts',
        ),
        migrations.DeleteModel(
            name='WorldNewsPosts',
        ),
    ]
