# Generated by Django 3.1.4 on 2021-12-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0012_auto_20211012_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditDevApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=25)),
                ('client_id', models.CharField(max_length=14)),
                ('client_secret', models.CharField(max_length=27)),
                ('user_agent', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Reddit Developer Applications',
                'abstract': False,
            },
        ),
    ]
