# Generated by Django 3.1.4 on 2021-12-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0014_auto_20211210_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=50)),
                ('fliter', models.CharField(max_length=10)),
                ('extracted_on', models.DateTimeField(auto_now=True)),
                ('num_posts', models.IntegerField()),
                ('status_code', models.IntegerField()),
                ('error_msg', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reddit ETL Logs',
                'ordering': ['extracted_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subreddits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('search_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Subreddits',
                'ordering': ['subreddit_name'],
                'abstract': False,
            },
        ),
    ]
