# Generated by Django 3.1.4 on 2021-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0015_redditlogs_subreddits'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditdevapps',
            name='active_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='redditdevapps',
            name='pipeline_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redditdevapps',
            name='pipeline_test_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redditdevapps',
            name='prod_interval',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='redditdevapps',
            name='test_interval',
            field=models.IntegerField(default=2),
        ),
    ]
