# Generated by Django 3.1.4 on 2021-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0017_auto_20211213_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_active', models.BooleanField(default=False)),
                ('active_modified', models.DateTimeField(auto_now=True)),
                ('pipeline_test_status', models.BooleanField(default=True)),
                ('test_interval', models.IntegerField(default=2)),
                ('prod_interval', models.IntegerField(default=12)),
            ],
            options={
                'verbose_name_plural': 'Reddit ETL Pipeline',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='redditdevapps',
            name='active_modified',
        ),
        migrations.RemoveField(
            model_name='redditdevapps',
            name='pipeline_active',
        ),
        migrations.RemoveField(
            model_name='redditdevapps',
            name='pipeline_test_status',
        ),
        migrations.RemoveField(
            model_name='redditdevapps',
            name='prod_interval',
        ),
        migrations.RemoveField(
            model_name='redditdevapps',
            name='test_interval',
        ),
    ]
