# Generated by Django 3.1.4 on 2021-12-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0018_auto_20211213_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditlogs',
            old_name='fliter',
            new_name='subreddit_filter',
        ),
    ]
