# Generated by Django 3.1.5 on 2021-02-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0002_securitypriceohlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypriceohlc',
            name='price_ohlc',
            field=models.FileField(null=True, upload_to='finance_api/ohlc'),
        ),
        migrations.AddField(
            model_name='securitypriceohlc',
            name='security_ticker',
            field=models.CharField(default='TEST', max_length=50),
        ),
        migrations.AddField(
            model_name='securitypriceohlc',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
