# Generated by Django 3.1.5 on 2021-02-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0003_auto_20210228_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitypriceohlc',
            options={'verbose_name_plural': 'Security OHLC Price Data'},
        ),
        migrations.AlterField(
            model_name='securitypriceohlc',
            name='security_ticker',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
