# Generated by Django 3.1.5 on 2021-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_auto_20210228_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitypriceohlc',
            name='id',
        ),
        migrations.AlterField(
            model_name='securitypriceohlc',
            name='security_ticker',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
