# Generated by Django 3.1.5 on 2021-03-04 13:55

from django.db import migrations, models
import finance_api.model_views_seralizers.securities_pricing.securities_pricing_storage


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0006_auto_20210228_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypriceohlc',
            name='price_ohlc',
            field=models.FileField(null=True, storage=finance_api.model_views_seralizers.securities_pricing.securities_pricing_storage.OHLCOverwriteStorage(), unique=True, upload_to='finance_api/ohlc'),
        ),
        migrations.AlterField(
            model_name='securitypriceohlc',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
