# Generated by Django 3.1.4 on 2021-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0008_wallstreetbetstickermentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASDAQComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=100, unique=True)),
                ('market_cap', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('ipo_year', models.PositiveSmallIntegerField()),
                ('sector', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'NASDAQ Index Composition',
            },
        ),
        migrations.CreateModel(
            name='NYSEComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=100, unique=True)),
                ('market_cap', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('ipo_year', models.PositiveSmallIntegerField()),
                ('sector', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'NYSE Index Composition',
            },
        ),
        migrations.AlterModelOptions(
            name='wallstreetbetstickermentions',
            options={'ordering': ['day'], 'verbose_name_plural': 'Wallstreetbets Ticker Mentions'},
        ),
        migrations.RenameField(
            model_name='wallstreetbetstickermentions',
            old_name='tickers',
            new_name='ticker_count',
        ),
    ]
