# Generated by Django 3.1.4 on 2021-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0009_auto_20210423_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdaqcomposition',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
