# Generated by Django 3.1.4 on 2021-04-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0011_auto_20210425_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdaqcomposition',
            name='market_cap',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nysecomposition',
            name='market_cap',
            field=models.FloatField(),
        ),
    ]
