# Generated by Django 3.1.4 on 2021-04-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0014_auto_20210425_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdaqcomposition',
            name='industry',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nasdaqcomposition',
            name='sector',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nysecomposition',
            name='industry',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nysecomposition',
            name='sector',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
