# Generated by Django 3.1.4 on 2021-04-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0016_auto_20210425_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdaqcomposition',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nysecomposition',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
