# Generated by Django 3.1.4 on 2021-05-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0017_auto_20210425_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdaqcomposition',
            name='company',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='nysecomposition',
            name='company',
            field=models.CharField(max_length=300),
        ),
    ]
