# Generated by Django 3.1.5 on 2021-02-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceposts',
            name='permalink',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wallstreetbetsposts',
            name='permalink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
