# Generated by Django 3.1.5 on 2021-02-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0002_auto_20210216_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceposts',
            name='id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallstreetbetsposts',
            name='id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
