# Generated by Django 3.1.5 on 2021-02-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210218_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='api_application',
            new_name='api_app',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='api_endpoint',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
