#########################################################
# The nginx server for managing django traffic.
#########################################################

FROM nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf
