# Generated by Django 3.1.4 on 2021-06-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('nlp_keywords', models.TextField()),
                ('published_date', models.DateField()),
                ('article_text', models.TextField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News Articles',
            },
        ),
    ]
