# Generated by Django 3.1.4 on 2021-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
