# Generated by Django 3.1.4 on 2021-06-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_auto_20210604_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='article_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
