# Generated by Django 3.1.5 on 2021-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIServices',
            fields=[
                ('app_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=200)),
                ('app_description', models.TextField()),
            ],
        ),
    ]
