# Generated by Django 3.1.5 on 2021-02-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apiservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIServices',
            new_name='APIApplication',
        ),
        migrations.AlterModelOptions(
            name='apiapplication',
            options={'verbose_name_plural': 'API Applications'},
        ),
    ]
